### ISSUE TITLE
是否支持持久化

### ISSUE THREAD

**Issue by zxcvbnmzsedr** [ytyht226/taskflow#1]
代码好像都是单个JVM中才可以使用，如果能够将运行中的状态进行持久化，那么即使jvm 被down掉也依然能够恢复回来
是否有后续的开发计划？

**Comment by zxcvbnmzsedr** [comment]
嗯嗯，我寻思着传统的BPMN强大但异常的复杂，如果依托于DAG的思想，那么无论是数据处理还是任务流转都能够很好的支持

**Comment by SuperChrisliu** [comment]
> 嗯嗯，我寻思着传统的BPMN强大但异常的复杂，如果依托于DAG的思想，那么无论是数据处理还是任务流转都能够很好的支持

dag跟BPMN的流程定义有缺别吗？感觉bpmn定义的xml应该也能转换一下到dag吧

**Comment by ytyht226** [comment]
> > 嗯嗯，我寻思着传统的BPMN强大但异常的复杂，如果依托于DAG的思想，那么无论是数据处理还是任务流转都能够很好的支持
> 
> dag跟BPMN的流程定义有区别吗？感觉bpmn定义的xml应该也能转换一下到dag吧

流程定义没有区别，都是用来描述任务依赖关系的；简单的流程定义bpmn的xml可以转换成taskflow的dag，两边的功能不完全一致，有些流程可能不能转换，比如taskflow中支持的弱依赖、条件判断、分支选择、节点组等能力，不清楚bpmn中是否也有类似功能，如果没有，则通过bpmn转换是使用不到这种功能的
