### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yinyinle** [ytyht226/taskflow#2]
op执行后的回调逻辑反了
 if (wrapper.getOperatorResult().getEx() != null) {    应该为 ==null
                    wrapper.getOperator().onSuccess(wrapper.getParam(), wrapper.getOperatorResult());
                } else {
                    wrapper.getOperator().onError(wrapper.getParam(), wrapper.getOperatorResult());
                }

**Comment by ytyht226** [comment]
问题已经修复

**Comment by ytyht226** [comment]
问题已经修复
