### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by jishuxx** [ytyht226/taskflow#3]
1、请问有提供可视化和配置化能力么？
2、采用线程池的方式，会不会导致CPU过高？有没有可能采用异步IO的编程模式？

**Comment by ytyht226** [comment]
> 1、请问有提供可视化和配置化能力么？ 2、采用线程池的方式，会不会导致CPU过高？有没有可能采用异步IO的编程模式？
1、现在建设的是引擎的核心能力，后续会提供使用DSL的方式基于已有的OP组件通过json配置的方式编排流程，再长期的目标会考虑提供可视化的配置能力，使用DSL或可视化的方式其实都是将配置解析成现在通过wrapper指定节点依赖的方式
2、使用线程池和CPU使用率没有必然联系，DAG图中每个节点内的逻辑其实主要分为两种：CPU密集型、IO密集型；如果是CPU密集型，CPU就是在做一些复杂运算，负载会很高，此时使用多线程的方式会充分利用多核的优势提升整体的性能；如果是IO密集型，比如大量的调用RPC服务，性能瓶颈在网络，使用多线程不会对CPU负载有什么影响，对于没有依赖关系的RPC调用使用多线程反而会降低流程的响应时延

**Comment by ytyht226** [comment]
> 1、请问有提供可视化和配置化能力么？ 2、采用线程池的方式，会不会导致CPU过高？有没有可能采用异步IO的编程模式？

1、现在建设的是引擎的核心能力，后续会提供使用DSL的方式基于已有的OP组件通过json配置的方式编排流程，再长期的目标会考虑提供可视化的配置能力，使用DSL或可视化的方式其实都是将配置解析成现在通过wrapper指定节点依赖的方式
2、使用线程池和CPU使用率没有必然联系，DAG图中每个节点内的逻辑其实主要分为两种：CPU密集型、IO密集型；如果是CPU密集型，CPU就是在做一些复杂运算，负载会很高，此时使用多线程的方式会充分利用多核的优势提升整体的性能；如果是IO密集型，比如大量的调用RPC服务，性能瓶颈在网络，使用多线程不会对CPU负载有什么影响，对于没有依赖关系的RPC调用使用多线程反而会降低流程的响应时延

**Comment by jishuxx** [comment]
> > 1、请问有提供可视化和配置化能力么？
> > 2、采用线程池的方式，会不会导致CPU过高？有没有可能采用异步IO的编程模式？
> 
> 1、现在建设的是引擎的核心能力，后续会提供使用DSL的方式基于已有的OP组件通过json配置的方式编排流程，再长期的目标会考虑提供可视化的配置能力，使用DSL或可视化的方式其实都是将配置解析成现在通过wrapper指定节点依赖的方式 2、使用线程池和CPU使用率没有必然联系，DAG图中每个节点内的逻辑其实主要分为两种：CPU密集型、IO密集型；如果是CPU密集型，CPU就是在做一些复杂运算，负载会很高，此时使用多线程的方式会充分利用多核的优势提升整体的性能；如果是IO密集型，比如大量的调用RPC服务，性能瓶颈在网络，使用多线程不会对CPU负载有什么影响，对于没有依赖关系的RPC调用使用多线程反而会降低流程的响应时延

你讲得挺对，请问有交流群么？可以一起研讨下。

**Comment by ytyht226** [comment]
> > > 1、请问有提供可视化和配置化能力么？
> > > 2、采用线程池的方式，会不会导致CPU过高？有没有可能采用异步IO的编程模式？
> > 
> > 
> > 1、现在建设的是引擎的核心能力，后续会提供使用DSL的方式基于已有的OP组件通过json配置的方式编排流程，再长期的目标会考虑提供可视化的配置能力，使用DSL或可视化的方式其实都是将配置解析成现在通过wrapper指定节点依赖的方式 2、使用线程池和CPU使用率没有必然联系，DAG图中每个节点内的逻辑其实主要分为两种：CPU密集型、IO密集型；如果是CPU密集型，CPU就是在做一些复杂运算，负载会很高，此时使用多线程的方式会充分利用多核的优势提升整体的性能；如果是IO密集型，比如大量的调用RPC服务，性能瓶颈在网络，使用多线程不会对CPU负载有什么影响，对于没有依赖关系的RPC调用使用多线程反而会降低流程的响应时延
> 
> 你讲得挺对，请问有交流群么？可以一起研讨下。

目前还没交流群，后面创建个，如果有问题想沟通的可以先发送邮件哈 ytyht226@163.com

**Comment by jishuxx** [comment]
你好，请问你在哪个城市？有打算换工作么？我们迫切需要你这样的人才来指导下我们。发自我的手机-------- 原始邮件 --------发件人： ytyht226 ***@***.***>日期： 2023年3月8日周三 13:00收件人： ytyht226/taskflow ***@***.***>抄送： jishuxx ***@***.***>, Author ***@***.***>主    题： Re: [ytyht226/taskflow] 请教 (Issue #3)



1、请问有提供可视化和配置化能力么？
2、采用线程池的方式，会不会导致CPU过高？有没有可能采用异步IO的编程模式？

1、现在建设的是引擎的核心能力，后续会提供使用DSL的方式基于已有的OP组件通过json配置的方式编排流程，再长期的目标会考虑提供可视化的配置能力，使用DSL或可视化的方式其实都是将配置解析成现在通过wrapper指定节点依赖的方式 2、使用线程池和CPU使用率没有必然联系，DAG图中每个节点内的逻辑其实主要分为两种：CPU密集型、IO密集型；如果是CPU密集型，CPU就是在做一些复杂运算，负载会很高，此时使用多线程的方式会充分利用多核的优势提升整体的性能；如果是IO密集型，比如大量的调用RPC服务，性能瓶颈在网络，使用多线程不会对CPU负载有什么影响，对于没有依赖关系的RPC调用使用多线程反而会降低流程的响应时延

你讲得挺对，请问有交流群么？可以一起研讨下。

目前还没交流群，后面创建个，如果有问题想沟通的可以先发送邮件哈 ***@***.***
