### ISSUE TITLE
DagEngine中CountDownLatch的使用顺序优化

### ISSUE THREAD

**Issue by JKTerrific** [ytyht226/taskflow#4]
https://github.com/ytyht226/taskflow/blob/0b47256b5061eaae10042a90811f3c3ffe6516b2/taskflow-core/src/main/java/org/taskflow/core/DagEngine.java#L436

syncLatch.countDown(); 
是否应该需要提前到finally的最开始进行执行。否则会出现无法正常结束DAG任务，一定需要等待到超时的情况

**Comment by JKTerrific** [comment]
最后一个wrapper阶段在执行到这句话之后就不会进行后续流程了   
DagContextHolder.putOperatorResult(wrapper.getId(), wrapper.getOperatorResult());

**Comment by JKTerrific** [comment]
![image](https://user-images.githubusercontent.com/17735912/224242666-70be58ef-c1ae-49f7-a113-86a6ef0f8c35.png)
![image](https://user-images.githubusercontent.com/17735912/224242731-23f99c2b-c764-4f74-8ee7-fb90387f6aff.png)

**Comment by ytyht226** [comment]
> 最后一个wrapper阶段在执行到这句话之后就不会进行后续流程了 DagContextHolder.putOperatorResult(wrapper.getId(), wrapper.getOperatorResult());

我这看着没问题，例子中3个节点依次串行执行，把你的代码分支提交个pr我看下？
![image](https://user-images.githubusercontent.com/7296427/224257266-2f864ec9-6b68-4c63-8a00-8e66224409fb.png)
![image](https://user-images.githubusercontent.com/7296427/224257348-ea5b645b-4d36-44d6-b378-9aef4ca88c5f.png)
