### ISSUE TITLE
移除对javafx的依赖

### ISSUE THREAD

**Issue by lozybean** [ytyht226/taskflow#8]
强依赖javafx-sdk，但只是用到了pair，可以使用更通用廉价的方案替代

**Comment by ytyht226** [comment]
> 强依赖javafx-sdk，但只是用到了pair，可以使用更通用廉价的方案替代

是的，后续会考虑替换pair，不然使用更高版本的jdk也是会有问题

**Comment by alyron** [comment]
有没有考虑对CompeletFuture  API做一些包装支持，
