### ISSUE TITLE
是否考虑对CompeletFuture API做一些包装支持，

### ISSUE THREAD

**Issue by alyron** [ytyht226/taskflow#9]
是否考虑对CompeletFuture API做一些包装支持，方便在大量有上面API的项目里引入支持

**Comment by ytyht226** [comment]
> 是否考虑对CompeletFuture API做一些包装支持，方便在大量有上面API的项目里引入支持

CompeletFuture只适合简单任务的编排，对于复杂场景的编排（强弱依赖、准入条件判断、分支选择等等）满足不了，当前框架基于DAG的方式实现，可以覆盖CompeletFuture的使用场景，后续不会考虑对CompeletFuture API的封装，如果业务场景比较简单，可以考虑直接使用CompeletFuture
